# Generated by Django 4.2.1 on 2023-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='products',
        ),
        migrations.AlterField(
            model_name='bludo',
            name='category',
            field=models.ManyToManyField(to='crm.category', verbose_name='Блюдо'),
        ),
    ]
