# Generated by Django 4.2.1 on 2023-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_dishes_products_alter_bludo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='products',
            field=models.CharField(default='Ech balya', max_length=200, verbose_name='Products'),
        ),
    ]
