# Generated by Django 4.2.1 on 2023-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_dishes_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_recipes',
            field=models.ManyToManyField(to='crm.dishes'),
        ),
    ]
